#! /bin/bash

#**********************************************************
#   Created on 2017-01-17 by liuxiaohu
#   
#   iptvstreaming       This shell scripts related to start
#                       and stop of the iptv streaming 
#                       process
#   
#   chkconfig: 2345 80 30
#   description: iptv streaming service
#
#**********************************************************

# source function library
#if [ -f /etc/init.d/functions ]; then
#    . /etc/init.d/functions
#elif [ -f /etc/rc.d/init.d/functions ]; then
#    . /etc/rc.d/init.d/functions
#else
#    exit 0
#fi
#
# source networking configuration
#. /etc/sysconfig/network

# check that networking is up
#[ "${NETWORKING}" = "no" ] && exit 0

# source iptv streaming functions
. /usr/local/IPTVStreaming/lib/functions

BASENAME=`basename $0`
RETVAL=0

# start all streams
start() {
    local count=`ps -ef|grep iptvd|grep -v grep|wc -l`
    if [ $count -eq 0 ]; then
        startAllStreams
        RETVAL=$?
    else
        echo -e "[\033[1;31mERROR:\033[0m] IPTVStreaming has been started, please try restart instead"
        RETVAL=1
    fi
    echo -n "start iptvstreaming: "
    [ $RETVAL -eq 0 ] && echo_success
    [ $RETVAL -eq 1 ] && echo_failure
    echo
    return $RETVAL
}

# stop all streams
stop () {
    local count=`ps -ef|grep iptvd|grep -v grep|wc -l`
    if [ $count -eq 0 ]; then
        echo -e "[\033[1;31mERROR:\033[0m] IPTVStremaing not running, please start first"
        RETVAL=1
    else
        stopAllStreams
        RETVAL=$?
    fi
    echo -n "stop iptvstreaming: "
    [ $RETVAL -eq 0 ] && echo_success
    [ $RETVAL -eq 1 ] && echo_failure
    echo
    return $RETVAL
}

# restart all streams
restart() {
    stop
    start
}

# status of all streams
iptvstatus() {
    local count=`ps -ef|grep iptvd|grep -v grep|wc -l`
    if [ $count -eq 0 ]; then
        echo -e "[\033[1;32mSTATUS:\033[0m]IPTVStreaming not running."
    else
        count=`ps -ef|grep ffmpeg|grep -v grep|wc -l`
        echo -e "[\033[1;32mSTATUS:\033[0m] IPTVStreaming is running. There are $count streams running."
    fi
}

# service command
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        iptvstatus
        ;;
    *)
        echo -e $"[\033[1;32mUsage:\033[0m] $BASENAME {start|stop|restart|status}"
        exit 1
esac

exit $?
